fontLato = sasl.gl.loadFont("globalAssets/fonts/Lato/lato.ttf")
fontLatoBold = sasl.gl.loadFont("globalAssets/fonts/Lato/latoBold.ttf")
fontLatoBlack = sasl.gl.loadFont("globalAssets/fonts/Lato/latoBlack.ttf")
fontRMbold = sasl.gl.loadFont("globalAssets/fonts/RobotoMono/RobotoMono-Bold-edited.ttf")
fontRM = sasl.gl.loadFont("globalAssets/fonts/RobotoMono/RobotoMono-Regular-edited.ttf")
fontRMmid = sasl.gl.loadFont("globalAssets/fonts/RobotoMono/RobotoMono-Medium-edited.ttf")
fontRMcompact = sasl.gl.loadFont("globalAssets/fonts/RobotoMono/RobotoMono-Compact-edited.ttf")
fontMR = sasl.gl.loadFont("globalAssets/fonts/MiriamLibre/MiriamLibre-Regular.ttf")
fontMRBold = sasl.gl.loadFont("globalAssets/fonts/MiriamLibre/MiriamLibre-Regular-e.ttf")
fontMRbold = sasl.gl.loadFont("globalAssets/fonts/MiriamLibre/MiriamLibre-Bold.ttf")
fontTest = sasl.gl.loadFont("globalAssets/fonts/Share/Share-Regular.ttf")
fontInconsolata = sasl.gl.loadFont(sasl.getXPlanePath() .. "/Resources/fonts/Inconsolata.ttf")
fontIB = fontInconsolata
-- fontShare = sasl.gl.loadFont(sasl.getXPlanePath() .. "/Resources/fonts/NotoSansCJK-SC-Regular.otf")
fontShare = sasl.gl.loadFont("globalAssets/fonts/Share/Share-Regular.ttf")
fontShareBold = sasl.gl.loadFont("globalAssets/fonts/Share/Share-Bold.ttf")
fontOxygen = sasl.gl.loadFont("globalAssets/fonts/Oxygen/Oxygen.ttf")
font7Seg = sasl.gl.loadFont("globalAssets/fonts/DSEG/DSEG7Classic-Bold.ttf")
-- Legacy Fonts
fmcFont3 = sasl.gl.loadFont("globalAssets/fonts/RobotoCondensed/RobotoCondensed-Regular.ttf")
-- (can be find/replaced later)
